---
- hosts: center
  gather_facts: no
  serial: 1
  tasks:
          - name: copy test.txt file
            copy:
                    src: /etc/ansible/test.txt
                    dest: /tmp/
                    mode: "0777"
