---
- hosts: center
  gather_facts: no
  tasks:
          - name: shell start
            shell: "df -h"
            register: data

          - name: debug
            debug:
                  msg: "{{ data.stdout_lines }}"
